# Generated by Django 5.1.6 on 2025-03-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
